SELECT * FROM FILME

DELETE FROM CLIENTES WHERE id = 3
DELETE FROM FILME WHERE id = 10

UPDATE CLIENTES SET NOME = 'Clarice Ribeiro' WHERE ID = 2

INSERT INTO CLIENTES(NOME,EMAIL,IDADE,SENHA,TELEFONE,ID_PLANO,ID_FORMA_DE_PAGAMENTO)
VALUES('Roberto Carlos','Robertocarlos06@hotmail.com',55,'32145678','83342599876',1,2)

INSERT INTO FILME
VALUES('Homem-Aranha 3 ', '02:37:05',1)